### ISSUE TITLE
Missing module `toolbox`

### ISSUE THREAD

**Issue by durka** [keunhong/kitnn#1]
I can't figure out what `toolbox` references here: https://github.com/keunhong/kitnn/blob/17e933f0a0d1e784260f6661c7aab525c444607e/kitnn/models/minc.py#L15

It's a rather generic name, so maybe I missed a PyPI package?

**Comment by durka** [comment]
It seems that replacing

```
from toolbox.images import resize
```

with

```
from skimage.transform import resize
```

is enough.

**Comment by keunhong** [comment]
Sorry, it looks like some of my research code leaked into this. I've separated the package [here](https://github.com/keunhong/toolbox/tree/0.2).

The [function itself](https://github.com/keunhong/rendkit/blob/master/toolbox/images.py#L131) is just a wrapper around the scipy function zoom, since some of the other resize functions changes the precision when converting which I didn't want.
